spring:
    profiles: container
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate

    datasource:
        url: jdbc:mysql://bootmysql:3000/bootdb
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver